### ISSUE TITLE
Use += for single item addition

### ISSUE THREAD

**Issue by flexatone** [brandtbucher/automap#1]
While `|=` works for adding an iterable of new keys (similar to `extend()` on a list), there is no way to add a single item without first wrapping it in an iterable. Perhaps (since we are favoring operators over methods for performance), `+=` can be  used for adding a single item.

**Comment by brandtbucher** [comment]
On further reflection, I still think that this feels like premature optimization and a bug magnet.

If we allowed the bare `+` operator to work too, we would be breaking with established conventions regarding operations between unrelated types:

```py
>>> AutoMap("ABC") | "D"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'automap.AutoMap' and 'str'
```

```py
>>> AutoMap("ABC") + "D"
automap.AutoMap(['A', 'B', 'C', 'D'])  # This works???
```

We're also fighting the precedent of using `+` and `+=` to concatenate sequences, so my first thought would be that it behaves like the existing `|` operator...

```py
>>> a = AutoMap("ABC")
>>> a
automap.AutoMap(['A', 'B', 'C'])
>>> a += "DEF"
>>> a
automap.AutoMap(['A', 'B', 'C', 'DEF'])
```

```py
>>> FrozenAutoMap("XY") + FrozenAutoMap("Z")
automap.FrozenAutoMap(['X', 'Y', automap.FrozenAutoMap(['Z'])])
```

There's no precedent for adding single elements like this with operators in other collection types, and wrapping a single item in a tuple of length one is _very_ cheap (a few nanoseconds), especially compared to the resizings that take place more often when inserting single items like this.

Let leave this be for now, and revisit later if it's still an issue. I'm open to adding an `add` method, though!

**Comment by flexatone** [comment]
Agreed: it is a rather unconventional use of the operator! It is, however, also conventional for such containers to have interfaces for adding both single items and iterables, so if if add() is the only option, lets go with that!

**Comment by brandtbucher** [comment]
I created `AutoMap.add` in 0a584db. 0.2.0 contains the change!

**Comment by brandtbucher** [comment]
0.3.0 adds an `update` method, as well.
