### ISSUE TITLE
0.5.2 Release

### ISSUE THREAD

**Issue by flexatone** [brandtbucher/automap#11]
Can we get a new release out with the new `NonUniqueError` exception? StaticFrame needs to catch that exception to prepare non-unique index messages. If you prefer a PR, let me know!

**Comment by brandtbucher** [comment]
[`0.6.0`](https://github.com/brandtbucher/automap/releases/tag/0.6.0) is out! This represents a pretty significant two-year refactoring, so please test it well and let me know if you encounter any issues.

**Comment by flexatone** [comment]
Excellent! I look forward to trying it out.

**Comment by flexatone** [comment]
Testing StaticFrame integration here:
https://github.com/InvestmentSystems/static-frame/pull/634
