### ISSUE TITLE
Raise different exception when AutoMap initialized with non-unique keys.

### ISSUE THREAD

**Issue by flexatone** [brandtbucher/automap#2]
Presently, an AutoMap initialized with non-unique keys raises a `KeyError`; perhaps a differerent Exception is better.

**Comment by brandtbucher** [comment]
I think `ValueError` makes sense, for the reasons we discussed.

**Comment by brandtbucher** [comment]
This was changed to a `ValueError` in bf932e6.

**Comment by brandtbucher** [comment]
0.1 is out with this change!
