### ISSUE TITLE
Remove .keys() unless .keys() returns a KeysView

### ISSUE THREAD

**Issue by flexatone** [brandtbucher/automap#4]
With dictionaries, we expect `for x in d` to have the same performance as `for x in d.keys()`. With AutoMap, `keys()` returns a tuple, which would give linear performance when using `in`. Perhaps better for avoiding confusion over this difference is to remove `keys()` entirely, and let users simply get a tuple of keys by calling `tuple()` on the AutoMap as needed.

Alternatively, it would be nice if `keys()` returned a `KeysView`, but avoiding that complexity may be desirable.

**Comment by brandtbucher** [comment]
I am pretty insistent on providing the full `Mapping` interface, which is what led me to define `keys`/`values`/`items`/`get` in the first place. Without `keys`, we also lose this great behavior:

```py
>>> from automap import AutoMap
>>> a = AutoMap("ABCD")
>>> dict(a)
{'A': 0, 'B': 1, 'C': 2, 'D': 3}
>>> {**a}
{'A': 0, 'B': 1, 'C': 2, 'D': 3}
>>> d = {}
>>> d.update(a)
>>> d
{'A': 0, 'B': 1, 'C': 2, 'D': 3}
```

It also looks like the built-in type that dict uses isn't friendly enough to solve this for us:

```
>>> dk = type({}.keys())
>>> dk
<class 'dict_keys'>
>>> dk(["A", "B", "C"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot create 'dict_keys' instances
```

So it's not immediately clear what the best path forward is.

**Comment by brandtbucher** [comment]
The `KeysView` interface is sort of an ordered set. An AutoMap without values is basically an ordered set, minus all of the fancy operators. So if we were to make an abstract parent class (`_Table`?) and create an `SequenceSet`(?) subclass, then we could reuse a lot of the machinery for the return type of `keys` and `items`. But those remaining set operators `&`/`&=`/`^`/`^=`/`-`/`-=`/`<`/`<=`/`>`/`>=` sound like a pain to implement. Hm.

**Comment by brandtbucher** [comment]
0.3.0 is out, and contains custom updating view types and iterators for `keys()`/`values()`/`items()`.
